### ISSUE TITLE
Manage .gitignore

### ISSUE THREAD

**Issue by carolynrehm** [revaturelabs/caliber-2-category-service#5]
@revaturelabs/1901-jan14-p3 
feature-category-service branch contains a .gitignore but it has merge conflicts and files which should be ignored are still in the repo. Please address this and clean up the branching structure - there seem to be some unnecessary branches

**Comment by peytonshriver** [comment]
Ill get that done right away.
Best Regards,
Peyton Shriver

**Comment by peytonshriver** [comment]
Cleaned up the feature branch, stray branches will be accessed and deleted tomorrow
